%disp('Establishing dataset details ...')
i = 0;
% i = i+1; %1
% db(i).mouseName    = 'M30';
% db(i).date          = '20191011';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 'An2';
% db(i).session       = 4;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 260;
% db(i).samplingRate  = 14.44; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'Trace 450 ms';
% db(i).trialDuration = 18; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

%% Multiple sessions
% i = i+1; %1
% db(i).mouseName    = 'M27';
% db(i).date          = '20190613';
% db(i).isDayOne      = 1; %1 - Yes; 0 - No
% db(i).sessionType   = 'An2';
% db(i).session       = 1;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 260;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 48; %usable trials
% db(i).comments      = 'TEC: 450 ms ISI';
% db(i).trialDuration = 18; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% i = i+1; %2
% db(i).mouseName    = 'M27';
% db(i).date          = '20190614';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 'An2';
% db(i).session       = 2;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 260;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 50; %usable trials
% db(i).comments      = 'TEC: 450 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
%  
% i = i+1; %3
% db(i).mouseName    = 'M27';
% db(i).date          = '20190615';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 'An2';
% db(i).session       = 3;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 260;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 450 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
%   
% i = i+1; %1
% db(i).mouseName    = 'M11';
% db(i).date          = '20170711';
% db(i).isDayOne      = 1; %1 - Yes; 0 - No
% db(i).sessionType   = 9;
% db(i).session       = 4;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.0V';
% db(i).nFrames       = 203;
% db(i).samplingRate  = 11.94; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 250 ms ISI; legacy protocol code';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
% 
% i = i+1; %4
% db(i).mouseName    = 'M11';
% db(i).date          = '20170712';
% db(i).isDayOne      = 1; %1 - Yes; 0 - No
% db(i).sessionType   = 11;
% db(i).session       = 1;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.0V';
% db(i).nFrames       = 203;
% db(i).samplingRate  = 11.94; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 450 ms ISI; legacy protocol code';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
% 
% i = i+1; %5
% db(i).mouseName    = 'M11';
% db(i).date          = '20170713';
% db(i).isDayOne      = 1; %1 - Yes; 0 - No
% db(i).sessionType   = 11;
% db(i).session       = 2;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.0V';
% db(i).nFrames       = 203;
% db(i).samplingRate  = 11.94; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 450 ms ISI; legacy protocol code';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

%% Reference I
% i = i+1; %1
% db(i).mouseName    = 'M26';
% db(i).date          = '20180508';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 5;
% db(i).session        = 1;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.47; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% i = i+1; %1
% db(i).mouseName    = 'M26';
% db(i).date          = '20180509';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 5;
% db(i).session       = 2;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.47; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

i = i+1; %1
db(i).mouseName    = 'M26';
db(i).date          = '20180514';
db(i).isDayOne      = 0; %1 - Yes; 0 - No
db(i).sessionType   = 5;
db(i).session       = 4;
db(i).diameter      = 8;
db(i).scanAmplitude = '1.8V';
db(i).nFrames       = 246;
db(i).samplingRate  = 14.47; %Hz
db(i).nTrials       = 60; %usable trials
db(i).comments      = 'TEC: 500 ms ISI';
db(i).trialDuration = 17; %in seconds
db(i).expts         = 1;
db(i).nplanes       = 1;
db(i).gchannel      = 1;
db(i).nplanes       = 1;
db(i).expred        = [];
db(i).nchannels_red = 0;

% i = i+1; %1
% db(i).mouseName    = 'M26';
% db(i).date          = '20180515';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 5;
% db(i).session       = 5;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.47; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% i = i+1; %1
% db(i).mouseName    = 'M26';
% db(i).date          = '20180516';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 5;
% db(i).session       = 6;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.47; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

%% Reference II
% i = i+1; %1
% db(i).mouseName    = 'M16';
% db(i).date          = '20171005';
% db(i).isDayOne      = 1; %1 - Yes; 0 - No
% db(i).sessionType   = 3;
% db(i).session       = 3;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.4V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.47; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 250 ms ISI; legacy protocol code';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

%% Misc
% i = i+1; %1
% db(i).mouseName    = 'G71';
% db(i).date          = '20190625';
% db(i).isDayOne      = 0; %1 - Yes; 0 - No
% db(i).sessionType   = 'So1';
% db(i).session       = 22;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 201;
% db(i).samplingRate  = 11.8; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'Soumya data';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

%% END
%disp ('... done!')