function jobData = harvestAnalyzedRealData(params)

if params.trim
    filename = sprintf('realDataAnalysis_method%s_batch_%i-%i_trimRun%i_trimmed.mat', ...
        params.methodList, ...
        params.sdcpStart, ...
        params.sdcpEnd, ...
        params.trimRun);
else
    filename = sprintf('realDataAnalysis_method%s_batch_%i-%i.mat', ...
        params.methodList, ...
        params.sdcpStart, ...
        params.sdcpEnd);
end

fullDirec4Read = strcat(params.fileLocation, filename);

fprintf('Harvesting %s ...\n', filename)
jobData = load(fullDirec4Read);
disp(' ... done!')

end