function jobData = harvestAnalyzedRealData(params)

if params.trim
    filename = sprintf('realDATAAnalysis_method%s_batch_%i-%i_trimRun%i_trimmed.mat', ...
        params.methodList, ...
        params.starti, ...
        params.endi, ...
        params.trimRun);
else
    filename = sprintf('realDATAAnalysis_method%s_batch_%i-%i.mat', ...
        params.methodList, ...
        params.starti, ...
        params.endi);
end

fullDirec4Read = strcat(params.fileLocation, filename);

fprintf('Harvesting %s ...\n', filename)
jobData = load(fullDirec4Read);
disp(' ... done!')

end