%disp('Establishing dataset details ...')
i = 0;
% i = i+1; %1
% dbase(i).mouseName    = 'M30';
% dbase(i).date          = '20191011';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 'An2';
% dbase(i).session       = 4;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 260;
% dbase(i).samplingRate  = 14.44; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'Trace 450 ms';
% dbase(i).trialDuration = 18; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

%% Multiple sessions
% i = i+1; %1
% dbase(i).mouseName    = 'M27';
% dbase(i).date          = '20190613';
% dbase(i).isDayOne      = 1; %1 - Yes; 0 - No
% dbase(i).sessionType   = 'An2';
% dbase(i).session       = 1;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 260;
% dbase(i).samplingRate  = 14.5; %Hz
% dbase(i).nTrials       = 48; %usable trials
% dbase(i).comments      = 'TEC: 450 ms ISI';
% dbase(i).trialDuration = 18; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

% i = i+1; %2
% dbase(i).mouseName    = 'M27';
% dbase(i).date          = '20190614';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 'An2';
% dbase(i).session       = 2;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 260;
% dbase(i).samplingRate  = 14.5; %Hz
% dbase(i).nTrials       = 50; %usable trials
% dbase(i).comments      = 'TEC: 450 ms ISI';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;
%  
% i = i+1; %3
% dbase(i).mouseName    = 'M27';
% dbase(i).date          = '20190615';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 'An2';
% dbase(i).session       = 3;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 260;
% dbase(i).samplingRate  = 14.5; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 450 ms ISI';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;
%   
% i = i+1; %1
% dbase(i).mouseName    = 'M11';
% dbase(i).date          = '20170711';
% dbase(i).isDayOne      = 1; %1 - Yes; 0 - No
% dbase(i).sessionType   = 9;
% dbase(i).session       = 4;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.0V';
% dbase(i).nFrames       = 203;
% dbase(i).samplingRate  = 11.94; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 250 ms ISI; legacy protocol code';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;
% 
% i = i+1; %4
% dbase(i).mouseName    = 'M11';
% dbase(i).date          = '20170712';
% dbase(i).isDayOne      = 1; %1 - Yes; 0 - No
% dbase(i).sessionType   = 11;
% dbase(i).session       = 1;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.0V';
% dbase(i).nFrames       = 203;
% dbase(i).samplingRate  = 11.94; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 450 ms ISI; legacy protocol code';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;
% 
% i = i+1; %5
% dbase(i).mouseName    = 'M11';
% dbase(i).date          = '20170713';
% dbase(i).isDayOne      = 1; %1 - Yes; 0 - No
% dbase(i).sessionType   = 11;
% dbase(i).session       = 2;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.0V';
% dbase(i).nFrames       = 203;
% dbase(i).samplingRate  = 11.94; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 450 ms ISI; legacy protocol code';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

%% Reference I
% i = i+1; %1
% dbase(i).mouseName    = 'M26';
% dbase(i).date          = '20180508';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 5;
% dbase(i).session       = 1;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 246;
% dbase(i).samplingRate  = 14.47; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 500 ms ISI';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

% i = i+1; %1
% dbase(i).mouseName    = 'M26';
% dbase(i).date          = '20180509';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 5;
% dbase(i).session       = 2;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 246;
% dbase(i).samplingRate  = 14.47; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 500 ms ISI';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

i = i+1; %1
dbase(i).mouseName    = 'M26';
dbase(i).date          = '20180514';
dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
dbase(i).sessionType   = 5;
dbase(i).session       = 4;
dbase(i).diameter      = 8;
dbase(i).scanAmplitude = '1.8V';
dbase(i).nFrames       = 246;
dbase(i).samplingRate  = 14.47; %Hz
dbase(i).nTrials       = 60; %usable trials
dbase(i).comments      = 'TEC: 500 ms ISI';
dbase(i).trialDuration = 17; %in seconds
dbase(i).expts         = 1;
dbase(i).nplanes       = 1;
dbase(i).gchannel      = 1;
dbase(i).nplanes       = 1;
dbase(i).expred        = [];
dbase(i).nchannels_red = 0;

% i = i+1; %1
% dbase(i).mouseName    = 'M26';
% dbase(i).date          = '20180515';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 5;
% dbase(i).session       = 5;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 246;
% dbase(i).samplingRate  = 14.47; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 500 ms ISI';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

% i = i+1; %1
% dbase(i).mouseName    = 'M26';
% dbase(i).date          = '20180516';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 5;
% dbase(i).session       = 6;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 246;
% dbase(i).samplingRate  = 14.47; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 500 ms ISI';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

%% Reference II
% i = i+1; %1
% dbase(i).mouseName    = 'M16';
% dbase(i).date          = '20171005';
% dbase(i).isDayOne      = 1; %1 - Yes; 0 - No
% dbase(i).sessionType   = 3;
% dbase(i).session       = 3;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.4V';
% dbase(i).nFrames       = 246;
% dbase(i).samplingRate  = 14.47; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'TEC: 250 ms ISI; legacy protocol code';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

%% Misc
% i = i+1; %1
% dbase(i).mouseName    = 'G71';
% dbase(i).date          = '20190625';
% dbase(i).isDayOne      = 0; %1 - Yes; 0 - No
% dbase(i).sessionType   = 'So1';
% dbase(i).session       = 22;
% dbase(i).diameter      = 8;
% dbase(i).scanAmplitude = '1.8V';
% dbase(i).nFrames       = 201;
% dbase(i).samplingRate  = 11.8; %Hz
% dbase(i).nTrials       = 60; %usable trials
% dbase(i).comments      = 'Soumya data';
% dbase(i).trialDuration = 17; %in seconds
% dbase(i).expts         = 1;
% dbase(i).nplanes       = 1;
% dbase(i).gchannel      = 1;
% dbase(i).nplanes       = 1;
% dbase(i).expred        = [];
% dbase(i).nchannels_red = 0;

%% END
%disp ('... done!')